### ISSUE TITLE
DB2 cursor.description does not get loaded/translated

### ISSUE THREAD

**Issue by DavidHrncir** [franz-see/Robotframework-Database-Library#131]
Connecting to DB2 instance, run a query, fetch all rows, go to inspect the "description" object for metadata, error occurs:
`TypeError: 'DBAPITypeObject' object is not iterable`

It throws an error while trying to parse the description in "jaydebeapi\__init__.py", class "Cursor", property "def description", line "m=self._meta".

Also noticed that the DBAPITypeObject looks different from that returned by "ibm_db" library.
ibm_db description structure:
`[['COLUMN_A', DBAPITypeObject({'BIGINT'}), 20, 20, 19, 0, False], ...`
jaydebeapi description structure:
`[('COLUMN_A', DBAPITypeObject('BIGINT'), 20, 20, 19, 0, 0), ...`

jaydebeapi version 1.1.1
JPype1 version 0.6.3

Any help would be appreciated.  Thanks!

**Comment by DavidHrncir** [comment]
Forgot to mention that in the debugger when trying to view the cursor object, that's where the error occurs...when it tries to load the properties.

**Comment by DavidHrncir** [comment]
Ah...may have just answered my own issue.  It is the structure difference that is causing one of the errors.  DBAPITypeObject is no longer iterable.  It has a "values" property containing a tuple of column types.  So good deal, but still do not know why the cursor raises an error when loading it's properties.

**Comment by jerry57** [comment]
What I have found over time is that not all drivers have implemented the DB API 2.0 spec (https://www.python.org/dev/peps/pep-0249/) the same way :)  i.e. there is a difference  when using pymssql and pyodbc (with MS SQL ODBC).  pyodbc has a much more accurate response than what pymssql implemented.  I suspect that your issue is going to be found between JayDeBeApi and the ibm_db jar file you are using.
