### ISSUE TITLE
Connect using custom params

### ISSUE THREAD

**Issue by pbreah** [franz-see/Robotframework-Database-Library#64]
Is there a way to use a Dictionary cursor with the keyword:

Connect To Database using Custom Params    pymysql     database='mydb', user='myuser', password='pass', host='192.168.10.10', port=3306, cursorclass=pymysql.cursors.DictCursor

I get the error:

NameError: name 'pymysql' is not defined

Even If I try to do:

Library     pymysql   (on the settings section, still doesn't work due to collisions of func names)

Any tips?

**Comment by jerry57** [comment]
I believe this is happening because the spacing between parameters is incorrect.  You need to have 2+ spaces after "Connect to Database Using Custom Params" and before pymysql and 2+ spaces after pymysql and the custom parameters string (custom params should be all one string which can contain single spaces).

**Comment by weikilla** [comment]
you can just use 
${result}    query    your_sql     returnAsDict=True
